DocManagerData:
   image: ubuntu
   volumes:
     - "/tmp/DOCManager"
     - "/tmp/DOCManager/temp"


haproxy:
   image: jantoniogc/docker-haproxy
   links:
     - "libreoffice:libreoffice"
   volumes:
     - /etc/haproxy/haproxy.cfg:/etc/haproxy/haproxy.cfg
   ports:
     - "8997:8997"
     - "1936:1936"

libreoffice:
   image: jantoniogc/docker-libreoffice
   environment:
     - TCP_PORTS=8997
   expose:
     - "8997"
   volumes_from:
     - DocManagerData
